name: test

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout And Build And Test
        run: |
          docker pull ubuntu:22.04
          sudo apt-get install -y inotify-tools
          curl -OL https://github.com/WojciechRynczuk/vcdMaker/releases/download/v3.0.2/vcdMaker-3.0.2-amd64.deb
          sudo apt-get install ./vcdMaker-3.0.2-amd64.deb
          sudo chmod -R 777 .
          ls -al
          ./run-single.sh
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: ./
